title: Balkrishna Rawool's blog
description: > # this means to ignore newlines until "baseurl:"
  This is my blog. I plan to put mainly technical stuff here.
  I like Java. So you can expect a lot of that here.
permalink: ':title/'
baseurl: # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Balkrishna Rawool # add your name
author-img: balkrishnarawool.png # add your photo
about-author: Software Engineer. Java, Spring, functional programming, data structures and algorithms are some of my interests.
social-twitter: BalaRawool # add your Twitter handle
#social-facebook: # add your Facebook handle
social-github: balkrishnarawool # add your Github handle
social-linkedin: balkrishnarawool # add your Linkedin handle
social-email: bala.rawool.blog@gmail.com # add your Email address

# Disqus
discus-identifier: discus-identifier # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 5
paginate_path: "/page/:num"
